using UnityEngine;

public class ParallaxBackground : MonoBehaviour
{
    // Start is called once before the first execution of Update after the MonoBehaviour is created

    private GameObject cam;
    [SerializeField] private float parallaxEffect;

    private float length;
    private float xPosition;

    void Start()
    {
        cam = GameObject.Find("Main Camera");

        length = GetComponent<SpriteRenderer>().bounds.size.x;
        xPosition = transform.position.x;

    }

    // Update is called once per frame
    void Update()
    {
        float distanceMoved = cam.transform.position.x * (1 - parallaxEffect);
        float distanceToMove = cam.transform.position.x * parallaxEffect;
        transform.position = new Vector3(xPosition + distanceToMove, transform.position.y);


        if (distanceMoved > xPosition + length)
        {
            xPosition = xPosition + length;
        }


    }
}
